name: Build and deploy Node.js project to Azure Function App - func-licenta

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write # <<< NECESAR pentru OIDC
  contents: read

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./api"
  NODE_VERSION: "18.x"

jobs:
  build:
    runs-on: ubuntu-latest
    # ... (restul build-ului tău)

  deploy:
    runs-on: ubuntu-latest
    # dacă nu pui permissions la nivel de workflow, pune-le aici:
    # permissions:
    #   id-token: write
    #   contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_293FBADD1AE74FA0AC096B8FAD2A3D8B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DD24A982B14A401FB3F3941A33074B38 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D6D02FBED4CF43C6AC4B761A0908057B }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: "func-licenta"
          package: "release.zip"
          scm-do-build-during-deployment: false
